- name: check if docker is installed
  shell: "docker -v"
  register: docker_exists
  ignore_errors: true

- name: Upgrade system
  apt:
    upgrade: dist
    update_cache: yes
  when: not docker_exists.stderr is regex("Docker version.*")

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  when: not docker_exists.stderr is regex("Docker version.*")

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  when: not docker_exists.stderr is regex("Docker version.*")

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: not docker_exists.stderr is regex("Docker version.*")

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when: not docker_exists.stderr is regex("Docker version.*")

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
  when: not docker_exists.stderr is regex("Docker version.*")

- name: Install Docker Module for Python
  pip:
    name: docker
