- name: run peerjs server container
  docker_container:
    name: peerjs
    image: peerjs/peerjs-server
    command: --port 9000 --allow_discovery --proxied 1 --alive_timeout 9000 --path /
    ports:
      - "9000:9000"

- name: create nginx configuration for peerjs.piranhalab.cc
  ansible.builtin.template:
    src: files/peerjs.conf
    dest: "/etc/nginx/sites-available/peerjs"

- name: Create symbolic link for peerjs.piranhalab.cc
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/peerjs"
    dest: "/etc/nginx/sites-enabled/peerjs"
    state: link

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
