- name: check if nginx is installed
  shell: "nginx -v" 
  register: nginx_exists
  ignore_errors: true

- name: Upgrade system
  apt: 
    upgrade: dist
    update_cache: yes
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: install dependencies
  apt: 
    name: "{{ item }}"
    state: latest
  loop: [ "build-essential", "libpcre3", "libpcre3-dev", "zlib1g", "zlib1g-dev", "libssl-dev", "libgd-dev", "libxml2", "libxml2-dev", "uuid-dev"]    
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: get nginx 1.20.1 version
  get_url: 
    url: http://nginx.org/download/nginx-1.20.1.tar.gz
    dest: /tmp/nginx.tar.gz
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: untar file
  unarchive:
    src: /tmp/nginx.tar.gz
    dest: /tmp/
    remote_src: yes
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: configure
  shell: 
    cmd: ./configure --prefix=/var/www/html --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-pcre  --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-http_ssl_module  --modules-path=/etc/nginx/modules --with-http_v2_module --with-stream=dynamic --with-http_addition_module --with-http_mp4_module
    chdir: /tmp/nginx-1.20.1
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: make nginx
  shell: 
    cmd: make 
    chdir: /tmp/nginx-1.20.1
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: make install nginx
  shell: 
    cmd: make install
    chdir: /tmp/nginx-1.20.1
  when: not nginx_exists.stderr is regex(".*1\.20\.1")

- name: Create sites-enabled directory 
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/
    state: directory

- name: Create sites-available directory 
  ansible.builtin.file:
    path: /etc/nginx/sites-available/ 
    state: directory

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: create nginx configuration for piranhalab.cc
  ansible.builtin.template:
    src: files/nginx.conf
    dest: "/etc/nginx/nginx.conf"
